name: Markdownlint

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup problem matcher
        uses: xt0rted/markdownlint-problem-matcher@v1
      - name: Run markdownlint
        run: npx --package markdownlint-cli -c 'markdownlint **/*.md --ignore node_modules --ignore src'
